export const NG_STATES = [
  { name: "Abia", code: "AB" },
  { name: "Adamawa", code: "AD" },
  { name: "Akwa Ibom", code: "AK" },
  { name: "Anambra", code: "AN" },
  { name: "Bauchi", code: "BA" },
  { name: "Bayelsa", code: "BY" },
  { name: "Benue", code: "BE" },
  { name: "Borno", code: "BO" },
  { name: "Cross River", code: "CR" },
  { name: "Delta", code: "DE" },
  { name: "Ebonyi", code: "EB" },
  { name: "Edo", code: "ED" },
  { name: "Ekiti", code: "EK" },
  { name: "Enugu", code: "EN" },
  { name: "Federal Capital Territory", code: "FC" }, // TODO: Confirm this price
  { name: "Gombe", code: "GO" },
  { name: "Imo", code: "IM" },
  { name: "Jigawa", code: "JI" },
  { name: "Kaduna", code: "KD" },
  { name: "Kano", code: "KN" },
  { name: "Katsina", code: "KT" },
  { name: "Kebbi", code: "KE" },
  { name: "Kogi", code: "KO" },
  { name: "Kwara", code: "KW" },
  { name: "Lagos", code: "LA" },
  { name: "Nasarawa", code: "NA" },
  { name: "Niger", code: "NI" },
  { name: "Ogun", code: "OG" },
  { name: "Ondo", code: "ON" },
  { name: "Osun", code: "OS" },
  { name: "Oyo", code: "OY" },
  { name: "Plateau", code: "PL" },
  { name: "Rivers", code: "RI" },
  { name: "Sokoto", code: "SO" },
  { name: "Taraba", code: "TA" },
  { name: "Yobe", code: "YO" },
  { name: "Zamfara", code: "ZA" },
] as const;

export const NG_STATE_DELIVERY_PRICES = {
  AB: 14000,
  AD: 14000,
  AK: 14000,
  AN: 14000,
  BA: 20000,
  BY: 14000,
  BE: 20000,
  BO: 20000,
  CR: 14000,
  DE: 14000,
  EB: 14000,
  ED: 14000,
  EK: 10000,
  EN: 14000,
  // FC: 14000,
  GO: 21000,
  IM: 14000,
  JI: 20000,
  KD: 20000,
  KN: 20000,
  KT: 20000,
  KE: 20000,
  KO: 14000,
  KW: 10000,
  LA: 8000,
  NA: 20000,
  NI: 20000,
  OG: 8000,
  ON: 8000,
  OS: 8000,
  OY: 8000,
  PL: 14000,
  RI: 14000,
  SO: 21000,
  TA: 21000,
  YO: 21000,
  ZA: 21000,
} as const;

export const NG_CITY_DELIVERY_PRICES = {
  OY: [
    {
      city: "Oyo",
      price: 6000,
    },
    ,
    {
      city: "Ibadan",
      price: 0,
    },
  ],
} as const;
